// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Sandbox from './Sandbox';
import SandboxNext from './SandboxNext';
import Text from './Text';

export {
	ContactForm,
	Image,
	Quote,
	Sandbox,
	SandboxNext,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	sandbox: Sandbox,
	sandbox_next: SandboxNext,
	text: Text,
};
